### ISSUE TITLE
add docs : { private: true }

### ISSUE THREAD

**Issue by mixmix** [ssbc/ssb-db#277]
several of these stream calls allows opts which include `{ private: true }` which is actually really handy!

task is to confirm which ones this is relevant to and update the docs

**Comment by mixmix** [comment]
examples : 
- `createLogStream`

**Comment by dominictarr** [comment]
all read methods support that. I remember being very careful to give full coverage after I changed sbot to handle the decryption.

**Comment by gmarcos87** [comment]
In which methods should we add this parameter in the documentation:
- [x] createLogStream
- [] createHistoryStream
- [] createFeedStream

Is that okay?

Related #279
