### ISSUE TITLE
Compression of data?

### ISSUE THREAD

**Issue by physkets** [ssbc/ssb-db#283]
_I'm making an issue here, because I can't find an IRC or Matrix dev channel. Is there an ssb thread/room/channel or something like that where such discussion takes place?_

Since SSB is a protocol that uses a sing linear chain of posts, and mandates localization of friend data, wouldn't it be useful to have all of that compressed? That will help reduce both he required bandwidth for transmission, as well as the storage requirements. You could use something modern like **zstd**.

Forgive me if this is already the case; I just could not find anything about this in the protocol.

**Comment by physkets** [comment]
Yes, it would still be nice to have at-rest as well as in-transit compression, at least for large files.

**Comment by christianbundy** [comment]
> I'm making an issue here, because I can't find an IRC or Matrix dev channel. Is there an ssb thread/room/channel or something like that where such discussion takes place?

Hi! There should be a `#scuttlebutt` channel on freenode, and there's also `#scuttebutt:matrix.org` if you're on Matrix. Are you having problems with the amount of space taken up on disk? I'm rewriting a bunch of SSB stuff from scratch and this is something on my mind.

**Comment by physkets** [comment]
Oh! Thanks for the pointer. I hadn't found it before. I've joined the IRC channel.

No, I'm not yet running into any issues, but I just thought that it made sense for a protocol like SSB.
