### ISSUE TITLE
docs — use with `ssb-server`

### ISSUE THREAD

**Issue by nichoth** [ssbc/ssb-db#314]
Hey. I was wondering if we could update the docs to show how to use this with `ssb-server` vs `secret-stack`, which the current docs show. 

Was uncertain if this is necessary actually. I've been using `ssb-server` without this plugin and it works. Leaving in the plugin seemed to cause errors actually, which is why it is now commented out [here](https://github.com/nichoth/eventual-gram-ssb/blob/main/src/server/index.js#L66) .

**Comment by cryptix** [comment]
Hmm... this was always a but confusing. If you look at the code of ssb-Server you can see that it’s mostly secret-stack+ssb-db (and some more application specific plugins)

but yes, if you don’t want to use ssb-server starring with stack+db is the way to go.
