### ISSUE TITLE
Incompatible with ssb-private

### ISSUE THREAD

**Issue by staltz** [ssbc/ssb-db#318]
I have both ssb-db and ssb-private installed, it seems that ssb-db version 20.3 makes ssb-private's streams not emit anything ever.

I'm on mobile now so I'll provide more details later, but I know that

- ssb db 20 and ssb-private 0.x dont work
- ssb db 20 and ssb-private 1.x dont work
- ssb db 19 and ssb-private 0.x works
- ssb db 19 and ssb-private 1.x works

**Comment by staltz** [comment]
Ok so it turns out I had to include `ssb-private1` as well. This wasn't clear from the docs or release notes, so I took the liberty to add this section "Breaking changes" to the release notes: 

https://github.com/ssbc/ssb-db/releases/tag/v20.0.1

cc @mixmix

**Comment by mixmix** [comment]
Cool, yeah sorry I thought I'd made it clear
